apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: messages-webservice
    context: /Users/hamid.poursepanj/Documents/projects/messages

deploy:
  helm:
    releases:
    - name: db
      namespace: default
      chartPath: bitnami/mongodb
      remote: true
      valuesFiles: [/Users/hamid.poursepanj/Documents/projects/messages/helm/db/values.yaml]
    - name: mws
      namespace: default
      chartPath: /Users/hamid.poursepanj/Documents/projects/messages/helm/messages
